// <auto-generated />
namespace CellPhone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class update_user_7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_user_7));
        
        string IMigrationMetadata.Id
        {
            get { return "202410300300021_update_user_7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
